/**
 * KMPDC facility types for discovery filtering.
 * Used with /healthcare/discovery/facilities and /healthcare/discovery/search (facilityType param).
 */
export const FACILITY_TYPES = [
  "BASIC HEALTH CENTRE",
  "COMPREHENSIVE CENTRE",
  "COTTAGE HOSPITAL",
  "COUNTY REFERRAL HOSPITAL",
  "DENTAL CENTRE",
  "DENTAL CLINIC",
  "DISPENSARY",
  "EYE CLINIC",
  "EYE HOSPITAL LEVEL 4",
  "EYE HOSPITAL LEVEL 5",
  "FAITH BASED DISPENSARY",
  "FAITH BASED LEVEL 4 HOSPITAL",
  "FAITH BASED LEVEL 5 HOSPITAL",
  "FAITH BASED SPECIALIZED TERTIARY REFERRAL HOSPITAL",
  "FAITH-BASED BASIC CENTRE",
  "FAITH-BASED COMPREHENSIVE CENTRE",
  "FUNERAL HOME (STAND ALONE)",
  "HEALTH CENTRE",
  "HOSPITAL LEVEL 4",
  "HOSPITAL LEVEL 4/INTERNSHIP TRAINING CENTRE/COUNTY HOSPITAL",
  "HOSPITAL LEVEL 5",
  "MATERNITY HOME",
  "MEDICAL CENTRE",
  "MEDICAL CLINIC",
  "MISSION HOSPITAL LEVEL 3",
  "MOBILE CLINIC",
  "NATIONAL TEACHING AND REFERRAL HOSPITAL",
  "NURSING HOME",
  "PRIVATE INTERNSHIP TEACHING AND REFERRAL HOSPITAL",
  "REHABILITATION CENTRE",
  "SECONDARY CARE HOSPITAL",
  "SPECIALIZED TERTIARY REFERRAL HOSPITAL",
  "SPECIALIZED TREATMENT CENTRE (LEVEL 4B)",
] as const

export type FacilityTypeOption = (typeof FACILITY_TYPES)[number]

export const FACILITY_LEVELS = [
  "LEVEL 2",
  "LEVEL 3A",
  "LEVEL 3B",
  "LEVEL 4",
  "LEVEL 4B",
  "LEVEL 5",
  "LEVEL 6A",
  "LEVEL 6B",
] as const

export type FacilityLevelOption = (typeof FACILITY_LEVELS)[number]
