import { useState, useCallback } from "react"
import { supabase } from "@/lib/supabase"
import { toast } from "@/hooks/useToast"
import { formatMoney } from "@/utilities/currencyUtilities"

type ReceiptStatus = "idle" | "loading" | "success" | "error"

export function useDownloadReceipt(transactionId: string | undefined) {
  const [status, setStatus] = useState<ReceiptStatus>("idle")

  const download = useCallback(async () => {
    if (!transactionId) return

    setStatus("loading")

    try {
      const { data: payment, error } = await supabase
        .from("payments")
        .select("*")
        .eq("id", transactionId)
        .single()

      if (error || !payment) throw new Error("Payment not found")

      const { default: jsPDF } = await import("jspdf")
      const { default: autoTable } = await import("jspdf-autotable")

      const doc = new jsPDF()
      const currency = payment.currency || "KES"
      const facilityName = payment.facility_name || "Care Provider"
      const userInfo = payment.user_info as { firstName?: string; lastName?: string } | null
      const patientName = userInfo
        ? `${userInfo.firstName ?? ""} ${userInfo.lastName ?? ""}`.trim()
        : "Patient"
      const createdAt = payment.created_at
        ? new Date(payment.created_at).toLocaleDateString("en-GB", {
            day: "numeric",
            month: "short",
            year: "numeric",
            hour: "2-digit",
            minute: "2-digit",
          })
        : "—"

      doc.setFontSize(20)
      doc.setFont("helvetica", "bold")
      doc.text("Jireh Health", 105, 20, { align: "center" })

      doc.setFontSize(12)
      doc.setFont("helvetica", "normal")
      doc.text("Payment Receipt", 105, 28, { align: "center" })

      doc.setDrawColor(200)
      doc.line(20, 33, 190, 33)

      let y = 42
      const labelX = 20
      const valueX = 80

      const addRow = (label: string, value: string) => {
        doc.setFont("helvetica", "normal")
        doc.setFontSize(10)
        doc.text(label, labelX, y)
        doc.setFont("helvetica", "bold")
        doc.text(value, valueX, y)
        y += 8
      }

      addRow("Date:", createdAt)
      addRow("Patient:", patientName)
      addRow("Provider:", facilityName)
      addRow("Amount:", formatMoney(payment.amount, currency))
      addRow("Status:", payment.status || "COMPLETED")
      addRow("Receipt #:", transactionId.substring(0, 8).toUpperCase())

      y += 4

      const splits = (payment.payment_splits ?? []) as Array<{
        paymentSplitAmount?: string
        wallet?: { type?: string }
      }>

      if (splits.length > 0) {
        doc.setDrawColor(200)
        doc.line(20, y, 190, y)
        y += 8

        doc.setFont("helvetica", "bold")
        doc.setFontSize(11)
        doc.text("Payment Sources", labelX, y)
        y += 8

        autoTable(doc, {
          startY: y,
          head: [["Source", "Amount"]],
          body: splits.map((s) => [
            s.wallet?.type || "—",
            formatMoney(Number(s.paymentSplitAmount) || 0, currency),
          ]),
          theme: "striped",
          headStyles: { fillColor: [79, 70, 229] },
          margin: { left: 20, right: 20 },
        })

        y = (doc as any).lastAutoTable.finalY + 10
      }

      const lineItems = (payment.line_items ?? []) as Array<{
        name?: string
        quantity?: number
        total?: number
      }>

      if (lineItems.length > 0) {
        doc.setFont("helvetica", "bold")
        doc.setFontSize(11)
        doc.text("Invoice Breakdown", labelX, y)
        y += 8

        autoTable(doc, {
          startY: y,
          head: [["Item", "Qty", "Amount"]],
          body: lineItems.map((item) => [
            item.name || "—",
            String(item.quantity ?? 1),
            formatMoney(item.total ?? 0, currency),
          ]),
          theme: "striped",
          headStyles: { fillColor: [79, 70, 229] },
          margin: { left: 20, right: 20 },
        })
      }

      doc.setFontSize(8)
      doc.setFont("helvetica", "italic")
      doc.text(
        "This receipt was generated by Jireh Health. For questions, contact support@jirehhealth.com",
        105,
        285,
        { align: "center" }
      )

      doc.save(`jireh-receipt-${transactionId.substring(0, 8)}.pdf`)

      setStatus("success")
      toast({
        title: "Receipt downloaded",
        description: "Your PDF receipt has been saved.",
      })
    } catch {
      setStatus("error")
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Unable to generate receipt. Please try again.",
      })
    }
  }, [transactionId])

  return { status, download }
}
